# Generated by Django 4.0.3 on 2023-01-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_alter_profile_previouswork_alter_profile_skills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='previousWork',
            new_name='previous_work',
        ),
    ]
